### ISSUE TITLE
Menu item is empty

### ISSUE THREAD

**Issue by nickstamas** [bomberstudios/sketch-framer#10]
The plugin is technically "showing up" but there's not name and the empty space there isn't clickable.

I'm using the newest Sketch Beta (2.4.0) and I'm on Mavericks.

https://www.dropbox.com/s/4poe5blz2pu6tsf/Screenshot%202013-11-01%2018.34.44.png

**Comment by Simcat** [comment]
Scripting no more!

![x1_stv_u5nenakrnqh2hv6grdijukzmqok98ep78_jk](https://cloud.githubusercontent.com/assets/1505159/9127400/47d15a22-3c6f-11e5-876f-4d4c361df031.png)
