### ISSUE TITLE
Detect Multiple Artboards

### ISSUE THREAD

**Issue by benjamindenboer** [bomberstudios/sketch-framer#102]
If we can see if a document has multiple artboards before importing, we can implement some form of selection.

**Comment by muditmittal** [comment]
Hi Ben, I love framer and am pretty excited about Framer-Sketch integration work! It would be pretty awesome if Framer natively provides support for multiple artboards. That ways I can continue building designs and prototype them along the way. To me, native support means: 
- I don't need to manually hide artboards, the topmost artboard in sketch is visible and others are hidden
- I can select an artboard from layer panel and have the viewer navigate to that artboard
- Symbols are supported the way Sketch handles them.

**Comment by bomberstudios** [comment]
Ping @benjaminnathan: just checking if you need anything from us to do this. I believe you can already get that info from Sketch using scripting or SketchTool, but I thought I'd ask just in case : )

**Comment by koenbok** [comment]
Building a UI around this is a bit overkill for it's functionality, for now I propose we use the \* flattening trick so it just becomes a flat layer.
