### ISSUE TITLE
Artboard Scaling

### ISSUE THREAD

**Issue by benjamindenboer** [bomberstudios/sketch-framer#103]
If we want to support scaling, we need to have the assets scaled _before_ importing, so they're always sharp. Then, you could work in @1x, @2x, @3x, and we can import it at whatever scale you'd like.

**Comment by bomberstudios** [comment]
That's a neat approach, and having an `exportScale` parameter for `framerExport` would solve this beautifully. I did a quick check of the code and it seems to be a trivial change.

**Comment by mrrocks** [comment]
Please YES :+1:
