### ISSUE TITLE
Index property within Layer declaration gets ignored

### ISSUE THREAD

**Issue by benjaminnathan** [bomberstudios/sketch-framer#74]
![index-property](https://cloud.githubusercontent.com/assets/869934/3996631/6f6ef00e-2937-11e4-8696-96a069bf3479.png)

**Comment by benjaminnathan** [comment]
This one still applies

**Comment by koenbok** [comment]
Framer bug :-)

**Comment by koenbok** [comment]
Fixed: https://github.com/koenbok/Framer/commit/efc5aa4810a605f1f9aec43161cce403b3ddd4f4
