### ISSUE TITLE
Mask without fill borks dimensions of layer contents

### ISSUE THREAD

**Issue by koenbok** [bomberstudios/sketch-framer#76]
A layer that is masked has the wrong frame. If you add a fill to the mask it gets the correct frame.

Sketch: http://cl.ly/2Y0O2B3O2e3G

![image](https://cloud.githubusercontent.com/assets/206779/4031849/e89875dc-2c6a-11e4-9d82-760bdd8e3ff8.png)

**Comment by benjaminnathan** [comment]
Further analysis:

(Sketch + Framer File: http://cl.ly/Zm14)

![bounds1](https://cloud.githubusercontent.com/assets/869934/6185986/5f2046a4-b374-11e4-9d41-041567c0d6d2.png)
![bounds2](https://cloud.githubusercontent.com/assets/869934/6185987/5f3c5858-b374-11e4-8c0e-daaac3f8081b.png)

**Comment by koenbok** [comment]
Simpler version of this issue: http://share.framerjs.com/x43u2ze0z2xo/

Repro: create a layer group with a mask that is larger than the contents and had no fill.

**Comment by koenbok** [comment]
This also fixes https://github.com/bomberstudios/sketch-framer/issues/83

**Comment by koenbok** [comment]
Fixed verified.
