### ISSUE TITLE
Layer group gets imported with the wrong size

### ISSUE THREAD

**Issue by wilsonminer** [bomberstudios/sketch-framer#77]
The layer group Card4 gets imported with 3px extra transparent pixels around each edge. The image is 566x726, whereas the shape in Sketch is 560x720.

Framer project and Sketch file: https://www.dropbox.com/s/2iop5se3yil0emp/20140822%20Card%20Dragging%20%28Framer%29.zip?dl=0

**Comment by koenbok** [comment]
Old and likely fixed. Going to close for now.
