### ISSUE TITLE
Exception importing

### ISSUE THREAD

**Issue by jornvandijk** [bomberstudios/sketch-framer#79]
Trying 127.0.0.1 8000 {"url": "http://192.168.1.22:8000", "signal": "ready"} Server ready at: http://192.168.1.22:8000 2014-10-03 15:35:47.793 coscript[65212:d07] framersketch running for com.bohemiancoding.sketch3 2014-10-03 15:35:47.823 coscript[65212:d07] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSDistantObject methodSignatureForSelector:]: remote object does not recognize selector: 'runPluginScript:'' *** First throw call stack: ( 0 CoreFoundation 0x00007fff8db4b25c __exceptionPreprocess + 172 1 libobjc.A.dylib 0x00007fff848fce75 objc_exception_throw + 43 2 CoreFoundation 0x00007fff8db4b10c +[NSException raise:format:] + 204 3 Foundation 0x00007fff851fbb87 -[NSDistantObject methodSignatureForSelector:] + 1179 4 coscript 0x0000000104ac6b1d MOBoxedObject_hasProperty + 1034 5 JavaScriptCore 0x00007fff8a790ef7 ZN3JSC16JSCallbackObjectINS_20JSDestructibleObjectEE18getOwnPropertySlotEPNS_6JSCellEPNS_9ExecStateENS_12PropertyNameERNS_12PropertySlotE + 407 6 JavaScriptCore 0x00007fff8a7aa656 ZNK3JSC7JSValue3getEPNS_9ExecStateENS_12PropertyNameERNS_12PropertySlotE + 198 7 JavaScriptCore 0x00007fff8a9f384c llint_slow_path_get_by_id + 220 8 JavaScriptCore 0x00007fff8a9fa51b llint_op_get_by_id + 107 9 JavaScriptCore 0x00007fff8a747ba6 _ZN3JSC11Interpreter7executeEPNS17ProgramExecutableEPNS_9ExecStateEPNS_8JSObjectE + 4134 10 JavaScriptCore 0x00007fff8a7469a6 ZN3JSC8evaluateEPNS_9ExecStateERKNS10SourceCodeENS_7JSValueEPS5 + 550 11 JavaScriptCore 0x00007fff8a74669d JSEvaluateScript + 477 12 coscript 0x0000000104ac9234 -[Mocha evalJSString:scriptPath:] + 161 13 coscript 0x0000000104ac9169 -[Mocha evalString:] + 29 14 coscript 0x0000000104adc43d -[COScript executeString:baseURL:] + 373 15 coscript 0x0000000104adb0a7 main + 494 16 libdyld.dylib 0x00007fff84aa05fd start + 1 ) libc++abi.dylib: terminating with uncaught exception of type NSException Traceback (most recent call last): File "/Applications/Framer Studio.app/Contents/Resources/framersketch/run.py", line 38, in output = run("./coscript run.js %s" % appIdentifier) File "/Applications/Framer Studio.app/Contents/Resources/framersketch/run.py", line 24, in run return subprocess.check_output(command, shell=True) File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 575, in check_output raise CalledProcessError(retcode, cmd, output=output) subprocess.CalledProcessError: Command './coscript run.js com.bohemiancoding.sketch3' returned non-zero exit status -6 Writing project to '/var/folders/qn/pyhws01n2sd99t6l5wm2zq5c0000gn/T/914E2E4F-86DE-437C-9D91-FAE0A77CE16F-65171-00009BEC852722C2/Untitled/imported/Design v2'

**Comment by koenbok** [comment]
Yeah this is Sketch crashing on an export. You can't really fix this without the original file. Also big chance that it already got fixed. Will close for now.
