### ISSUE TITLE
Issues with symbols [cannot repro]

### ISSUE THREAD

**Issue by koenbok** [bomberstudios/sketch-framer#82]
https://www.facebook.com/groups/framerjs/permalink/628714697255605/

After debugging with Cemre, we found that there is an issue with Symbols.
When you turn something into a symbol, it's child layers don't react to attributes being changed.

Example 
File: http://cl.ly/451Y053w0h44
While visible is false on TGSubgroup, it's still visible in the viewer.

**Comment by bomberstudios** [comment]
Right, Symbols are treated differently on some parts of the exporter, so I'm probably doing something wrong there. Will check

**Comment by koenbok** [comment]
Thanks!

**Comment by benjaminnathan** [comment]
I cannot reproduce this. I tested creating new Symbols or used previously defined Symbols, and all seem to correctly respect any visual changes within Sketch (opacity, x, y) and properties (visibility, opacity) within Framer as well.

**Comment by koenbok** [comment]
@cemre can you remember how we could repro this?

**Comment by koenbok** [comment]
Ok at this point we don't have a solid way to repro this, which means that it is quite an edge case. @bomberstudios if you could indeed glance over the code to see if we miss something obvious that would be great.

**Comment by koenbok** [comment]
Also pinging @miekd to see if he still has the linked file.
