### ISSUE TITLE
Add a way to make bounds larger than the actual image pixels

### ISSUE THREAD

**Issue by koenbok** [bomberstudios/sketch-framer#83]
https://www.facebook.com/groups/framerjs/permalink/630438713749870/

> Hi guys, Framer or Sketch seems to ignore transparent layers inside the group when exporting. I wanted to include the transparent bounds to have a bigger tap area - like the example below instead 
of 192x128, it will only export 27x40. Is there another way to do this?

**Comment by bomberstudios** [comment]
I had this in sketch-generator:

> If you add a "@bounds" layer at the bottom of your layer group, it will be used for dimensions but won't get exported

We could either do something like that, or simply make the exporter export transparent layers as real layers, with opacity set to 0 in Framer. I probably have this filed as an issue already.

**Comment by koenbok** [comment]
I think taking into account transparent layers might be a nice way to do it, but I might be overlooking some edge case.

**Comment by koenbok** [comment]
Imho, this is a nice to have, but not a serious bug at this point.

**Comment by koenbok** [comment]
Pretty sure this is fixed with https://github.com/bomberstudios/sketch-framer/issues/76

**Comment by koenbok** [comment]
Fixed verified
