### ISSUE TITLE
Sketch puts out images with $ prefix

### ISSUE THREAD

**Issue by koenbok** [bomberstudios/sketch-framer#84]
Not sure what these are, but they break uploading.

```
$DISTANCE1415797057614-2A2F4ED0-1986-40FC-B6C9-7FADC6A603DF.png
$DISTANCE1415797057614-9CE344F0-21B7-4974-905F-80C1D202C6FE.png
$DISTANCE1415797057614-812BB089-20F3-4A3D-AF07-ADC617FB9C84.png
$DISTANCE1415797057614-909ADD1C-1F04-4193-8FDB-F3D3F274164C.png
$DISTANCE1415797057614-8988237D-A71E-48BB-A00E-5761A4788073.png
$DISTANCE1415797057614-F425A2D0-1F45-4FD3-9E64-D7EDC1E2907D.png
$DISTANCE1415797127438-580806D8-62A8-4EB0-A839-768F4A6EA987.png
$DISTANCE1415797127438-E125BB6F-772D-4C58-BEDA-392C00B6D66F.png
$DISTANCE1415797127438-E488E61C-B10C-45A7-8174-01B67D585B7D.png
$DISTANCE1415797166472-1E146DA5-3B93-45A6-A6A4-E1C0F8C085F9.png
```

**Comment by bomberstudios** [comment]
Do we have a sample document? Is the user using any of the spec plugins (sketch-measure, Sketch-Notebook…)?

**Comment by koenbok** [comment]
I'll mail it to you.

**Comment by bomberstudios** [comment]
FTR, those names are created by https://github.com/utom/sketch-measure

The complete list is:

- $SIZE
- $WIDTH
- $HEIGHT
- $DISTANCE
- $PROPERTY
- $LABEL
- $OVERLAYER
- $COORDINATE

We will simply ignore layers named like that

**Comment by koenbok** [comment]
Ah, good to know! Thanks!

**Comment by koenbok** [comment]
@pieteromvlee what is the best thing to do here?

- I can ignore them at upload, risking that they might be actual layers
- We could have some naming prefix/mangling
- Ideally we detect these and don't include them in the export
