### ISSUE TITLE
Hidden layers are no longer imported

### ISSUE THREAD

**Issue by benjaminnathan** [bomberstudios/sketch-framer#85]
Sketch + Framer file: http://cl.ly/ZhdI

Previously, layer groups with visibility toggled within Sketch would get imported with Opacity and Visible set to 0 and False respectively. Now, while visible is set to files, a transparent image actually gets imported, so the image never appears.

![visiblity](https://cloud.githubusercontent.com/assets/869934/6126602/8a4e54fa-b122-11e4-8735-fd6dae2c0631.png)

**Comment by koenbok** [comment]
This is not working as expected.

Let's ignore all opacity, and just get visible working.

#### Current

Sketch
- Layer group visible: false
- Layer group opacity: 1

layers.json
- Layer group visible: true
- Layer group opacity: 0

#### Expected

Sketch
- Layer group visible: false
- Layer group opacity: 1

layers.json
- Layer group visible: false
- Layer group opacity: 1

**Comment by koenbok** [comment]
![image](https://cloud.githubusercontent.com/assets/206779/6352119/979ac250-bc40-11e4-94cf-86e62232c5d0.png)

**Comment by pieteromvlee** [comment]
Considered fixed! :)
