### ISSUE TITLE
Multiple Sketch Files open breaks Import

### ISSUE THREAD

**Issue by benjaminnathan** [bomberstudios/sketch-framer#86]
Sketch + Framer File: http://cl.ly/Zm14

With one .sketch document open, importing works. When I open another Sketch file, and place it on the background, and either try to import the same file or re-import it, it doesn't work. It doesn't seem to matter whether or not the file has any layers or contents whatsoever.

#### Reproduction Steps

1. Open a sketch file.
2. Import it.
3. Open another one, bring to background.
4. Try to re-import the same, previous sketch file. (Or import it within a new document)
5. Script Error

![error](https://cloud.githubusercontent.com/assets/869934/6186085/5fec37f4-b375-11e4-8b3d-cf5b18dac862.png)

**Comment by benjaminnathan** [comment]
Wanted to get to the root of this, and did some more testing. It's curious because it seems random. Perhaps it has something to do with which sketch document was created first?

#### Scenario
1. I create two identical Sketch files. FileA and FileB. Both are identical, except for the fill color, and name. First I make & save FileA, then FileB.

2. I bring fileB to foreground and import it. Importing works.
![filebworks](https://cloud.githubusercontent.com/assets/869934/6189178/ef3fd870-b398-11e4-9ca9-9d53b0e42c62.png)

3. I bring fileA to foreground and import it. Now, I get a Script Error.
![fileadoesnt](https://cloud.githubusercontent.com/assets/869934/6189209/2eccbf1c-b399-11e4-8543-d3f339ec73cc.png)

4. Ah, actually, I think I see what's happening now! It somehow imports the file from FileB instead of FileA, yet looks for the image from FileA.
![itlooksforthewrongfile](https://cloud.githubusercontent.com/assets/869934/6189261/8e880240-b399-11e4-90cc-9797df37478f.png)

(Note how it has imported the green layer (from FileB) while I imported FileA. It also references layerB in the JSON.

![wrongfile](https://cloud.githubusercontent.com/assets/869934/6189290/cfbd86b8-b399-11e4-9656-22b32173b9ce.png)

**Comment by benjaminnathan** [comment]
Download the 2 Sketch and Framer Files: http://cl.ly/Zn6X

**Comment by koenbok** [comment]
Ok I'm pretty sure that I know what goes on here.

Initially, I thought Framer wasn't detecting the active/current document if you had >1 open. But it actually does.

What happens is that the internal code that we run on Sketch `[doc exportFramer]` doesn't run on the current/active document.

To repro:

- Download @benjaminnathan s examples
- Open File A
- Import
- Open File B

You'll see that it actually exported File A again, while File B is the current/active document.

**Comment by koenbok** [comment]
Verified fixed.
