### ISSUE TITLE
Empty layer groups still get images (resulting in 404)

### ISSUE THREAD

**Issue by benjaminnathan** [bomberstudios/sketch-framer#87]
Sketch + Framer: http://cl.ly/ZlhD

#### Case

1) Simple document with Artboard and a Symbol
![sketch](https://cloud.githubusercontent.com/assets/869934/6186172/84ded214-b376-11e4-9004-4431fa850111.png)

2) Gets imported correctly, without errors
![framer](https://cloud.githubusercontent.com/assets/869934/6186184/98fae1e8-b376-11e4-8e9e-9f73b4bc303f.png)

3) Web Inspector reveals the following:
![error](https://cloud.githubusercontent.com/assets/869934/6186187/a266526c-b376-11e4-8fc9-fa4bf8caed6a.png)

4)  After removing the "status bar contents" folder within Sketch:
![error2](https://cloud.githubusercontent.com/assets/869934/6186233/2538dc1e-b377-11e4-85da-c4961c299862.png)

It appears to also be looking for the app bar + status bar image, which in Sketch is simply a layer group containing two other layer groups with actual contents:
![sketch2](https://cloud.githubusercontent.com/assets/869934/6186278/a002480e-b377-11e4-919f-0ff4cd8de2a4.png)

It also appears to be looking for the Artboard image.

![artboard](https://cloud.githubusercontent.com/assets/869934/6186282/b87c661c-b377-11e4-8385-ba59f22fed86.png)

Changing these Artboard background/export settings doesn't change that. Removing the artboards leaves us only with the error of it looking for the "app bar + status bar" image.

5) What's interesting is that when we ungroup the layers within "app bar + status bar" - a new error appears, this time it starts looking for "app bar contents" - which now only contains the "menu" icon:

![appbar](https://cloud.githubusercontent.com/assets/869934/6186333/5ccbff52-b378-11e4-8aee-dff0798bc734.png)
![error3](https://cloud.githubusercontent.com/assets/869934/6186335/61fca422-b378-11e4-9e85-4d0c3c43e336.png)

6) Finally, ungrouping the "menu" icon, leaving only the actual Shape layer within the " app bar contents" folder gives us an error-free web inspector.

![sketch3](https://cloud.githubusercontent.com/assets/869934/6186367/badc3198-b378-11e4-82b1-5d06e2b3391c.png)

**Comment by koenbok** [comment]
A simpler version is here (including sketch file). Tldr; layer groups without image (but maybe including other layer groups) should not include images.

**Comment by koenbok** [comment]
Another example: http://share.framerjs.com/3xsowpgw51qh/

Layer "Empty" should not get an image in the json file here.

**Comment by pieteromvlee** [comment]
Fixed!

**Comment by koenbok** [comment]
Looks like this is fixed.

**Comment by koenbok** [comment]
We only need to figure out what happens with:

- Layer groups with only layer groups and a mask WITH fill (should export image)
- Layer groups with only layer groups and a mask WITHOUT fill (should not export image)

**Comment by koenbok** [comment]
Verified.
