### ISSUE TITLE
Hidden Child Layers get wrong Frame 

### ISSUE THREAD

**Issue by benjaminnathan** [bomberstudios/sketch-framer#92]
#### Sketch + Framer File: http://cl.ly/aIB7

In the Sketch file, we have a Group named **table** containing two **tableRows** - each with a checkbox that has a **selected** and **default** state. (*All with the same layer names, too.*)

If we hide one of the **selected** layer groups, it gets 200px extra padding, whilst getting imported at the correct size.
![diff](https://cloud.githubusercontent.com/assets/869934/6728716/170e9622-ce2c-11e4-971e-a9164e0fcff4.png)

#### Correct properties:
- x:24, y: 228
- width: 46, height: 46

#### Properties it gets:
- x:-76, -41
- width: 246, height: 246

**Comment by benjaminnathan** [comment]
It's getting those properties because this is effectively what is happening:
![getx](https://cloud.githubusercontent.com/assets/869934/6728950/4abb4de2-ce2e-11e4-94ac-2335ecf35b12.png)

- The image is positioned correctly, but offset by the padding, this getting different x and y properties
- The padding is transparent, it doesn't get any background

**Comment by leggett** [comment]
I **think** I'm having the same problem. At least, layers that are hidden in Sketch are imported with 200px of padding into Framer. Took me forever to figure out the bug happens on hidden layers.

**Comment by benjamindenboer** [comment]
Fixed!
