### ISSUE TITLE
Improve scaled artboard situation

### ISSUE THREAD

**Issue by koenbok** [bomberstudios/sketch-framer#96]
Since Sketch switched to points vs. pixels, we have a lot of people confused when exporting them.

@benjaminnathan explains it best here:
https://www.facebook.com/groups/framerjs/permalink/691634997630241/

How could we make this more straight forward?

References:
https://www.facebook.com/groups/760188533992744/permalink/998374860174109/
https://www.facebook.com/groups/framerjs/permalink/683194658474275/
https://www.facebook.com/groups/framerjs/permalink/641286459331762/
https://www.facebook.com/groups/framerjs/permalink/640739382719803/

**Comment by patrickkeenan** [comment]
For all my prototypes I define scale(S=3) at the beginning of my code. Then whenever I have a unit I use 360*S. It's painful. I would recommend using density independent pixels like the Google material spec. This makes it easy to work at any density. Maybe it could be a Framer global variable?

**Comment by mrrocks** [comment]
Actually if you set a different size (2x, 3x, etc) for your assets in Sketch, they actually get exported to Framer at that specific size. The real problem is positions (x, y), they remain at 1x on the JSON file.

**Comment by koenbok** [comment]
Thanks for the input!

**Comment by koenbok** [comment]
Also be sure to check out @peteschaffners pull request: https://github.com/koenbok/Framer/pull/228

**Comment by bomberstudios** [comment]
This would be solved nicely by #103, so maybe this one can be closed?
